---
title: "DTA_L3_RMD Practice"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Tree Heights in British Columbia

```{r chunk_trees, eval = TRUE, echo = TRUE}
library(tidyverse)

#Generate normal distribution of 80 points, mean of 20, SD = 2
tree_height = rnorm(80, 20, 2)

#Find log of tree heights
log_tree_height = log(tree_height)

#Organize datasets in neat tibble frame, define as la_df
la_df = tibble(tree_height, log_tree_height)

#create histogram with ggplot package, referencing tidy dataset la_df
ggplot(la_df, aes(x = tree_height)) + geom_histogram()

#create another histogram
hist(tree_height, main = "Tree Height in BC", ylab = "# of trees")
```

###Age of Household Hamsters

```{r}
hamster_ages = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)
mean (hamster_ages)

boxplot(hamster_ages, main = "Hamster Ages", ylab = "Age(years)", ylim = c(0,30))

hist(hamster_ages, main = "Hamsters can live a long time", ylab = "so many young hamsters", xlab = "Hamster Ages", col = "green")

wavy_hamsters = sin(hamster_ages)

la_df = tibble (hamster_ages, wavy_hamsters)

ggplot(la_df, aes(x = hamster_ages, y = wavy_hamsters)) + geom_point(col = "red", size = 8, main = "ham")
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
